name: Build website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1 
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Hydrogen'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --force 

      - name: Build website
        run: |
          npm run lint --fix
          npm run export
          touch ./out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
