name: Build website (test)

on:
  # push:
  #  branches: [ main ]
  # pull_request:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --pure-lockfile    

      - name: Build website
        run: |
          yarn run export
          touch ./docs/.nojekyll

      - name: Push website build
        run: |
          git add docs/**
          git diff-index --quiet HEAD || git commit -m 'Deploy ${{ github.sha }}'
          git push 
